services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

  job-track-original:
    image: ${DOCKER_IMAGE_NAME}
    container_name: job-track-original
    depends_on:
      - mongodb
    environment:
        - OPEN_API_KEY=${OPEN_API_KEY}
        - SPRING_PROFILES_ACTIVE=prod
        - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
    ports:
      - "8080:8080"
    volumes:
      - /home/deploy/data:/app/files
    pull_policy: never

volumes:
  mongo_data:
    driver: local