services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: VerySecretPassword1986
      MONGO_INITDB_DATABASE: job-track
    volumes:
      - mongo_data:/data/db

  faiss-api:
    image: faiss-faiss-api:latest
    container_name: faiss-api
    ports:
      - "8001:8001"
    volumes:
      - ./faiss_data:/app/faiss_data
      - /home/deploy/faiss/app:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  job-track-original:
    image: jobtrack:latest
    container_name: job-track-original
    depends_on:
      - mongodb
    environment:
        - SPRING_PROFILES_ACTIVE=stg
        - SEARCH_SERVICE_URL=${SEARCH_SERVICE_URL}
        - OPEN_API_KEY=${OPEN_API_KEY}
        - SPRING_DATA_MONGODB_URI=mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track?authSource=admin
        - SPRING_SSL_ENABLED=true
        - SPRING_SSL_CERTIFICATE=/etc/ssl/certs/xpatjob.co.uk.crt
        - SPRING_SSL_CERTIFICATE_PRIVATE_KEY=/etc/ssl/certs/private.key
        - SPRING_SSL_TRUST_CERTIFICATE=/etc/ssl/certs/xpatjob.co.uk.ca-bundle.crt
    ports:
      - "8443:8443"
    volumes:
      - /home/deploy/data:/app/files
      - /home/deploy/certs:/etc/ssl/certs
    pull_policy: never

  postgres:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=superKeycloak!123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=superAdmin!123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=superKeycloak!123
      - KC_HOSTNAME=62.171.139.86
    ports:
      - "8085:8080"
    depends_on:
      - postgres

volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local
