services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: VerySecretPassword1986
      MONGO_INITDB_DATABASE: job-track
    volumes:
      - mongo_data:/data/db
    networks:
      - dev_network

  faiss-api:
    image: faiss-faiss-api:latest
    container_name: faiss-api
    ports:
      - "8001:8001"
    volumes:
      - ./faiss_data:/app/faiss_data
      - /home/deploy/faiss/app:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    networks:
      - dev_network

  job-track-original:
    image: jobtrack:latest
    container_name: job-track-original
    depends_on:
      - mongodb
    environment:
        - SPRING_PROFILES_ACTIVE=stg
        - SEARCH_SERVICE_URL=${SEARCH_SERVICE_URL}
        - OPEN_API_KEY=${OPEN_API_KEY}
        - SPRING_DATA_MONGODB_URI=mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track?authSource=admin
        - SPRING_SSL_ENABLED=true
        - SPRING_SSL_CERTIFICATE=/etc/ssl/certs/xpatjob.co.uk.crt
        - SPRING_SSL_CERTIFICATE_PRIVATE_KEY=/etc/ssl/certs/private.key
        - SPRING_SSL_TRUST_CERTIFICATE=/etc/ssl/certs/xpatjob.co.uk.ca-bundle.crt
    ports:
      - "8843:8843"
    volumes:
      - /home/deploy/data:/app/files
      - /home/deploy/certs:/etc/ssl/certs
    pull_policy: never
    networks:
      - dev_network

  postgres:
    image: postgres:latest
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=superKeycloak!123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    networks:
      - dev_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=superKeycloak!123
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=superAdmin!123
      - KC_PROXY=edge
      - KC_HTTP_RELATIVE_PATH=/keycloak
      - KC_HOSTNAME=xpatjob.co.uk
      - KC_HOSTNAME_URL=https://xpatjob.co.uk/keycloak
      - KC_HOSTNAME_ADMIN_URL=https://xpatjob.co.uk/keycloak
      - KC_HOSTNAME_STRICT=false
      - KEYCLOAK_FRONTEND_URL=https://xpatjob.co.uk/keycloak
    expose:
      - "8080:8080"
    volumes:
      - /home/deploy/certs:/opt/keycloak/certs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dev_network



  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    ports:
      - "8088:80"
      - "443:443"
    volumes:
      - /home/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/deploy/certs:/etc/nginx/certs
    networks:
      - dev_network
    depends_on:
      - keycloak

volumes:
  mongo_data:
    driver: local
  postgres_data1:
    driver: local
networks:
  dev_network:
    driver: bridge
