spring:
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
search:
  service:
    url: http://62.171.139.86:8001
open:
  api:
    key: ${OPEN_API_KEY}