spring:
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
  docker:
    compose:
      enabled: true
      file: docker-compose-local.yaml
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
search:
  service:
    url: http://62.171.139.86:8001
open:
  api:
    key: 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