server:
  port: 8080

spring:
  application:
    name: job-track
  jackson:
    serialization:
      indent-output: true
  main:
    allow-circular-references: true
  batch:
    jdbc:
      initialize-schema: always
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/job-track
    username: admin
    password: password
    pool:
      initial-size: 10
      max-size: 20
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/job-track
    username: admin
    password: password
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 60000

open:
  api:
    key: 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





