spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/job-track?authSource=admin
      database: job-track
      username: admin
      password: VerySecretPassword1986
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
search:
  service:
    url: http://62.171.139.86:8001
open:
  api:
    key: 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