spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/job-track
      database: job-track
      username: admin
      password: VerySecretPassword1986

search:
  service:
    url: ${SEARCH_SERVICE_URL}

open:
  api:
    key: ${OPEN_API_KEY}
