server:
  port: 8088
spring:
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: ${KEYCLOAK_SERVICE_URL}
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
      auto-index-creation: true
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
  ssl:
    enabled: false
    certificate: /etc/ssl/certs/xpatjob.co.uk.crt
    certificate-private-key: /etc/ssl/certs/private.key
    trust-certificate: /etc/ssl/certs/xpatjob.co.uk.ca-bundle.crt
search:
  service:
    url: ${SEARCH_SERVICE_URL}
open:
  api:
    key: ${OPEN_API_KEY}

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
