spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/job-track
    username: admin
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/job-track
    username: admin
    password: password

  docker:
    compose:
      enabled: false

open:
  api:
    key: ${OPEN_API_KEY}
