spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/job-track
    username: admin
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/job-track
    username: admin
    password: password
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml

open:
  api:
    key: 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
