server:
  port: 8088
spring:
  kafka:
    admin:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
      group-id: jobTrackConsumerGroup
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ToStringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        fetch.max.bytes: 500000000 # 500MB
        max.partition.fetch.bytes: 500000000 # 500MB
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.springframework.kafka.support.serializer.ToStringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.request.size: 500000000 # 500MB
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: ${KEYCLOAK_SERVICE_URL}
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
  ssl:
    enabled: false
    certificate: /etc/ssl/certs/xpatjob.co.uk.crt
    certificate-private-key: /etc/ssl/certs/private.key
    trust-certificate: /etc/ssl/certs/xpatjob.co.uk.ca-bundle.crt
search:
  service:
    url: ${SEARCH_SERVICE_URL}
open:
  api:
    key: ${OPEN_API_KEY}

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
