spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/job-track
    username: admin
    password: password
  data:
    mongodb:
      uri: mongodb://mongodb:27017/job-track
      database: job-track
      username: admin
      password: password

  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
search:
  service:
    url: http://localhost:8001

open:
  api:
    key: ${OPEN_API_KEY}
