spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/job-track
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/job-track
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  docker:
    compose:
      enabled: true

open:
  api:
    key: ${OPEN_API_KEY}
