spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/job-track?authSource=admin
      database: job-track
      username: admin
      password: VerySecretPassword1986
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
search:
  service:
    url: http://62.171.139.86:8001
open:
  api:
    key: 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