server:
  port: 8080

spring:
  ssl:
    enabled: false
  application:
    name: job-track
  jackson:
    serialization:
      indent-output: true
  main:
    allow-circular-references: true
  threads:
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: 60000
  codec:
    max-in-memory-size: 10MB
