spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/job-track
      database: job-track
      username: admin
      password: VerySecretPassword1986

search:
  service:
    url: http://62.171.139.86:8001

open:
  api:
    key: ${OPEN_API_KEY}
