server:
  netty:
    ignored-malformed-requests: false

#  port: 8443
#  ssl:
#    enabled: false
#    key-store-type: PKCS12
#    key-store: classpath:ssl/localhost.p12
#    key-store-password: passwordpassword

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/realms/offerland-realm-app/protocol/openid-connect/certs
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
      auto-index-creation: true
  docker:
    compose:
      enabled: true
      file: docker-compose-local.yaml

  logging:
    level:
      org:
        springframework:
          cache: DEBUG
search:
  service:
    url: http://62.171.139.86:8001
open:
  api:
    key: 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

stripe:
  secret:
    key:
