server:
  port: 8443
spring:
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
  logging:
    level:
      org:
        springframework:
          cache: INFO
  ssl:
    enabled: true
    certificate: /etc/ssl/certs/xpatjob.co.uk.crt
    certificate-private-key: /etc/ssl/certs/private.key
    trust-certificate: /etc/ssl/certs/xpatjob.co.uk.ca-bundle.crt
search:
  service:
    url: ${SEARCH_SERVICE_URL}
open:
  api:
    key: ${OPEN_API_KEY}
