spring:
  data:
    mongodb:
      uri: mongodb://admin:VerySecretPassword1986@mongodb:27017/job-track
  logging:
    level:
      org:
        springframework:
          cache: DEBUG
search:
  service:
    url: ${SEARCH_SERVICE_URL}
open:
  api:
    key: ${OPEN_API_KEY}